[phases.build]
  nixPkgs = ['nodejs-20_x', 'npm']
  
[nixpacks.providers]
  Nixpacks = {}
  
[phases.install]
  cmds = ['npm ci']
  
[staticAssets]
  isStaticAsset = '''
  (path includes "dist" || path includes "build") && 
  !path.match(".*\\.(map|ts|tsx|js|jsx)$")
  '''

